import type { Finding, Trail } from "../types"

// ── Generic helpers ────────────────────────────────────────────────────────────

export function downloadBlob(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Defer revoke so the download has actually started in slower browsers.
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }
  } catch {
    // Fall through to legacy path.
  }
  // Fallback for HTTP / older browsers — works on every desktop browser since 2015.
  const ta = document.createElement("textarea")
  ta.value = text
  ta.style.position = "fixed"
  ta.style.opacity = "0"
  document.body.appendChild(ta)
  ta.select()
  let ok = false
  try {
    ok = document.execCommand("copy")
  } catch {
    ok = false
  }
  document.body.removeChild(ta)
  return ok
}

const slug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")

export const findingAnchorId = (f: Finding) =>
  `finding-${slug(f.lobbyist_name)}-${slug(f.agency_short)}`

export const trailAnchorId = (t: Trail) => `trail-${slug(t.case_id)}`

// CSV: standard RFC 4180 quoting — wrap in "…" only when needed, escape "" inside.
function csvCell(v: unknown): string {
  if (v === null || v === undefined) return ""
  const s = String(v)
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`
  return s
}

function csvRows(rows: (string | number | null | undefined)[][]): string {
  return rows.map((r) => r.map(csvCell).join(",")).join("\r\n")
}

// ── Findings ───────────────────────────────────────────────────────────────────

const FINDING_COLS: (keyof Finding)[] = [
  "rank", "score", "lobbyist_name", "registrant_name", "agency_short",
  "concentration", "agency_filings", "total_filings", "covered_position",
  "n_clients", "total_income", "first_year", "last_year",
  "top_clients_str", "sample_uuid", "senate_lda_url", "verification_status",
]

export function findingsToCsv(findings: Finding[]): string {
  const header = FINDING_COLS as string[]
  const rows = findings.map((f) => FINDING_COLS.map((k) => f[k] ?? ""))
  return csvRows([header, ...(rows as (string | number | null | undefined)[][])])
}

export function findingToMarkdown(f: Finding): string {
  const pct = (f.concentration * 100).toFixed(1)
  const incomeM = (f.total_income / 1_000_000).toFixed(2)
  const ldaUrl = f.senate_lda_url ?? (f.sample_uuid
    ? `https://lda.senate.gov/filings/public/filing/${f.sample_uuid}/print/`
    : "(no UUID on file)")
  const trail = f.trail
  const trailBlock = trail
    ? [
        "",
        "## Money trail (USAspending)",
        `**Total traced:** $${trail.total.toLocaleString()} across ${trail.n_clients_with_awards}/${trail.n_clients_total} clients`,
        `**Discretionary:** $${trail.discretionary_total.toLocaleString()} · **Routine:** $${trail.routine_total.toLocaleString()}`,
        "",
        "| Client | Total | Awards | Discretionary |",
        "|--------|------:|-------:|--------------:|",
        ...trail.clients.map(
          (c) =>
            `| ${c.label} | $${c.total.toLocaleString()} | ${c.n_awards} | $${c.discretionary_amount.toLocaleString()} |`
        ),
      ].join("\n")
    : ""
  return [
    `# ${f.lobbyist_name} → ${f.agency_short.toUpperCase()}`,
    "",
    `- **Rank:** ${f.rank}`,
    `- **Firm:** ${f.registrant_name}`,
    `- **Agency concentration:** ${pct}% (${f.agency_filings} of ${f.total_filings} filings)`,
    `- **Disclosed income:** $${incomeM}M across ${f.n_clients} clients`,
    `- **Active:** ${f.first_year}–${f.last_year}`,
    `- **FairGuard score:** ${f.score.toFixed(2)}`,
    `- **Verification:** ${f.verification_status ?? "unverified"}`,
    "",
    `## Prior role (verbatim LDA self-disclosure)`,
    "",
    `> ${f.covered_position}`,
    "",
    `## Top clients targeting ${f.agency_short.toUpperCase()}`,
    "",
    f.top_clients_str || "(none recorded)",
    "",
    `## Source`,
    "",
    `Senate LDA UUID: \`${f.sample_uuid ?? "—"}\``,
    `Filing record: ${ldaUrl}`,
    `Source file: \`${f.sample_source}\``,
    trailBlock,
    "",
    "---",
    `_Generated by FairGuard. Verify independently before publishing._`,
    "",
  ].join("\n")
}

export function findingCitation(f: Finding): string {
  const pct = (f.concentration * 100).toFixed(1)
  const ldaUrl = f.senate_lda_url ?? (f.sample_uuid
    ? `https://lda.senate.gov/filings/public/filing/${f.sample_uuid}/print/`
    : "")
  return (
    `${f.lobbyist_name} (${f.registrant_name}) directed ${f.agency_filings} of ` +
    `${f.total_filings} lobbying filings (${pct}%) at the ${f.agency_short.toUpperCase()}. ` +
    `Source: U.S. Senate LDA filing ${f.sample_uuid ?? "(no UUID)"}` +
    (ldaUrl ? ` — ${ldaUrl}` : "") +
    `. Compiled by FairGuard.`
  )
}

// ── Trails ─────────────────────────────────────────────────────────────────────

export function trailToCsv(t: Trail): string {
  const header = ["client", "total", "n_awards", "discretionary_amount", "routine_amount", "recipients"]
  const rows = t.clients.map((c) => [
    c.label, c.total, c.n_awards, c.discretionary_amount, c.routine_amount,
    c.recipients.join("; "),
  ])
  return csvRows([header, ...(rows as (string | number)[][])])
}

export function trailsToCsv(trails: Trail[]): string {
  // One row per (trail × client) — wide enough to pivot in a spreadsheet.
  const header = [
    "case_id", "lobbyist_label", "agency", "award_groups", "generated_at",
    "client", "client_total", "client_awards", "client_discretionary", "client_routine",
    "trail_total", "trail_discretionary_total", "trail_routine_total",
  ]
  const rows: (string | number)[][] = []
  for (const t of trails) {
    const base = [
      t.case_id, t.lobbyist_label, t.agency, t.award_groups.join("|"), t.generated_at,
    ]
    if (!t.clients.length) {
      rows.push([...base, "", 0, 0, 0, 0, t.total, t.discretionary_total, t.routine_total])
      continue
    }
    for (const c of t.clients) {
      rows.push([
        ...base,
        c.label, c.total, c.n_awards, c.discretionary_amount, c.routine_amount,
        t.total, t.discretionary_total, t.routine_total,
      ])
    }
  }
  return csvRows([header, ...rows])
}

export function trailToMarkdown(t: Trail): string {
  const pctDisc = t.total > 0 ? Math.round((t.discretionary_total / t.total) * 100) : 0
  const matchLine = t.match?.length
    ? `**Linked to:** ${t.match.map((m) => `${m.lobbyist_name} (${m.agency_short.toUpperCase()})`).join(", ")}`
    : ""
  return [
    `# Money trail: ${t.lobbyist_label}`,
    "",
    `- **Agency:** ${t.agency}`,
    `- **Award groups:** ${t.award_groups.join(", ")}`,
    `- **Total traced:** $${t.total.toLocaleString()}`,
    `- **Discretionary:** $${t.discretionary_total.toLocaleString()} (${pctDisc}%)`,
    `- **Routine:** $${t.routine_total.toLocaleString()}`,
    `- **Clients with awards:** ${t.n_clients_with_awards} of ${t.n_clients_total}`,
    `- **Generated:** ${t.generated_at}`,
    matchLine,
    "",
    "| Client | Total | Awards | Discretionary | Routine | Recipient(s) on file |",
    "|--------|------:|-------:|--------------:|--------:|----------------------|",
    ...t.clients.map(
      (c) =>
        `| ${c.label} | $${c.total.toLocaleString()} | ${c.n_awards} | $${c.discretionary_amount.toLocaleString()} | $${c.routine_amount.toLocaleString()} | ${c.recipients.join("; ")} |`
    ),
    "",
    t.misses.length ? `_No verified ${t.agency} ${t.award_groups.join(", ")} found for: ${t.misses.join(", ")}._` : "",
    "",
    "---",
    "_Conflict-of-interest structure, not proven wrongdoing. Verify program type, §207 status, and seek comment before publishing._",
    "",
  ].filter((l) => l !== null && l !== undefined).join("\n")
}

export function trailCitation(t: Trail): string {
  return (
    `${t.lobbyist_label} clients received $${t.total.toLocaleString()} from the ` +
    `${t.agency} (${t.award_groups.join(", ")}, ` +
    `${t.discretionary_total.toLocaleString()} discretionary). ` +
    `Source: USAspending.gov, recipient-name-verified by FairGuard. ` +
    `Generated ${t.generated_at}.`
  )
}
