/**
 * FairGuard Reporter Verification UI — Main Page
 *
 * Data source: web/public/findings.json
 * Generated by: uv run scripts/03_agency_concentration.py
 *
 * To refresh: re-run the script. The JSON is updated automatically.
 * To start the UI: cd web && npm run dev → http://localhost:3000
 */

// findings.json is written by scripts/03_agency_concentration.py
// If it doesn't exist yet, run: uv run scripts/03_agency_concentration.py
import rawData from "../../public/findings.json"
import FindingsClient from "./FindingsClient"

// ── Types ──────────────────────────────────────────────────────────────────────

interface Finding {
  rank: number
  score: number
  agency_short: string
  lobbyist_name: string
  registrant_name: string
  covered_position: string
  concentration: number
  agency_filings: number
  total_filings: number
  n_clients: number
  total_income: number
  first_year: number
  last_year: number
  top_clients_str: string
  sample_uuid: string
  sample_source: string
  senate_lda_url: string | null
  verification_status?: "verified" | "partial" | "unverified" | null
}

interface FindingsPayload {
  generated_at: string
  total_candidates: number
  findings: Finding[]
}

// ── Page (Server Component — data loading only) ────────────────────────────────

export default function Page() {
  const data = rawData as FindingsPayload
  const findings: Finding[] = data.findings ?? []

  // Unique agencies in ranked order (for filter chips)
  const agencies = [...new Set(findings.map((f) => f.agency_short))]

  const generatedAt = data.generated_at
    ? new Date(data.generated_at).toLocaleString("en-US", {
        month: "short", day: "numeric", year: "numeric",
        hour: "2-digit", minute: "2-digit", timeZoneName: "short",
      })
    : null

  return (
    <div>
      {/* Page header */}
      <div className="mb-8">
        <div className="mb-3 flex flex-wrap items-center gap-2">
          <span className="rounded-full bg-red-100 px-3 py-1 text-xs font-semibold text-red-700">
            Track 2 — Structural finding
          </span>
          {generatedAt && (
            <span className="text-xs text-slate-400">
              Data generated: {generatedAt}
            </span>
          )}
        </div>
        <h1 className="mb-3 text-3xl font-bold tracking-tight text-slate-900">
          Former Agency Officials Lobbying Their Former Agency
        </h1>
        <p className="max-w-2xl text-slate-600">
          {data.total_candidates} candidates identified across 18 federal agencies.
          Ranked by agency concentration ratio × volume × seniority.
          All figures from Senate LDA 2022-2026. Prior roles are verbatim
          self-disclosures — verify independently before publishing.
        </p>

        {/* Refresh instruction */}
        <div className="mt-4 inline-block rounded-lg bg-slate-100 px-4 py-2 text-xs font-mono text-slate-600">
          To refresh data: <span className="text-blue-700">uv run scripts/03_agency_concentration.py</span>
          {" "}→ restart dev server
        </div>
      </div>

      {/* Interactive findings + filter (client component handles state) */}
      {findings.length === 0 ? (
        <div className="rounded-xl border border-dashed border-slate-300 p-14 text-center">
          <p className="mb-2 font-semibold text-slate-600">No findings loaded</p>
          <p className="text-sm text-slate-400">
            Run{" "}
            <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono">
              uv run scripts/03_agency_concentration.py
            </code>{" "}
            to generate <code className="font-mono">web/public/findings.json</code>
          </p>
        </div>
      ) : (
        <FindingsClient findings={findings} agencies={agencies} />
      )}

      {/* Editorial footer */}
      <div className="mt-10 rounded-xl border border-amber-200 bg-amber-50 p-5">
        <p className="mb-1 text-sm font-semibold text-amber-900">Editorial note</p>
        <p className="text-sm text-amber-800">
          This interface is for reporter verification, not publication. Concentration
          ratios are computed from <strong>Senate LDA only</strong> (House not yet
          included — would shift rankings). The{" "}
          <code className="font-mono text-xs">covered_position</code> field is a
          voluntary self-disclosure: lobbyists fill it in themselves. Always confirm
          prior roles against authoritative sources (agency staff directories, news
          archives) before making any public claim. See{" "}
          <code className="font-mono text-xs">notes/05_finding_bridenstine.md §2.5</code>{" "}
          for verification methodology.
        </p>
      </div>
    </div>
  )
}
